[project]
name = "bi-p-uni"
version = "0.0.1"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.7",
    "pandas[excel]>=2.3.3",
    "seaborn>=0.13.2",
]

[dependency-groups]
dev = [
    "ipykernel>=7.0.1",
    "ruff>=0.14.1",
]
